// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv'
import { defineConfig } from 'prisma/config'

// В монорепо единственный источник правды по окружению — apps/platform/.env.
// Prisma CLI всегда запускается с cwd = packages/db (через turbo/pnpm --filter),
// поэтому путь задаётся относительно него.
config({ path: '../../apps/platform/.env' })

export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
})
